# Generated by Django 3.1.11 on 2021-05-21 19:18

from django.db import migrations


def populate_currencies(apps, schema_editor):
    Currency = apps.get_model('currencies', 'Currency')
    currencies = (
        {'code': "EUR", 'name': "Euro", 'symbol': "€"},
        {'code': "CHF", 'name': "Swiss Franc", 'symbol': "CHF"},
        {'code': "USD", 'name': "Euro", 'symbol': "$"},
        {'code': "GBP", 'name': "Euro", 'symbol': "£"},
    )
    [Currency.objects.create(**i) for i in currencies]


def remove_currencies(apps, schema_editor):
    Currency = apps.get_model('currencies', 'Currency')
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_currencies, remove_currencies)
    ]
