# Generated by Django 3.1.11 on 2021-05-22 23:22

from django.db import migrations


def populate_providers(apps, schema_editor):
    Provider = apps.get_model('currencies', 'Provider')
    providers = (
        {
            'name': "Fixer", 'slug': "fixer", 'default': True,
            'path': "nucoro_currency.currencies.utils.adapters.fixer.FixerAdapter"
        },
        {
            'name': "Mock", 'slug': "mock", 'default': False,
            'path': "nucoro_currency.currencies.utils.adapters.mock.MockAdapter",
        },
    )
    [Provider.objects.create(**i) for i in providers]


def remove_providers(apps, schema_editor):
    Provider = apps.get_model('currencies', 'Provider')
    Provider.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0003_provider'),
    ]

    operations = [
        migrations.RunPython(populate_providers, remove_providers)
    ]
